### ISSUE TITLE
broken in 1.8.x

### ISSUE THREAD

**Issue by helptiger** [Rustywolf/NightLamp#2]
[19:10:49] [Server thread/INFO]: fehlfarben issued server command: /addlamp
[19:10:50] [Server thread/INFO]: Placed blocks registered!
[19:10:50] [Server thread/WARN]: java.lang.NoSuchFieldException: isStatic
[19:10:50] [Server thread/WARN]:        at java.lang.Class.getField(Unknown Source)
[19:10:50] [Server thread/WARN]:        at codes.rusty.nightlamp.util.WorldUtil.getStatic(WorldUtil.java:102)
[19:10:50] [Server thread/WARN]:        at codes.rusty.nightlamp.util.WorldUtil.setLampState(WorldUtil.java:20)
[19:10:50] [Server thread/WARN]:        at codes.rusty.nightlamp.tasks.LampSetStateTask.run(LampSetStateTask.java:18)
[19:10:50] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[19:10:50] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[19:10:50] [Server thread/WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:722)
[19:10:50] [Server thread/WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[19:10:50] [Server thread/WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653)
[19:10:50] [Server thread/WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556)
[19:10:50] [Server thread/WARN]:        at java.lang.Thread.run(Unknown Source)
[19:10:50] [Server thread/WARN]: java.lang.NoSuchFieldException: isStatic
[19:10:50] [Server thread/WARN]:        at java.lang.Class.getField(Unknown Source)
[19:10:50] [Server thread/WARN]:        at codes.rusty.nightlamp.util.WorldUtil.setStatic(WorldUtil.java:112)
[19:10:50] [Server thread/WARN]:        at codes.rusty.nightlamp.util.WorldUtil.setLampState(WorldUtil.java:23)
[19:10:50] [Server thread/WARN]:        at codes.rusty.nightlamp.tasks.LampSetStateTask.run(LampSetStateTask.java:18)
[19:10:50] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[19:10:50] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[19:10:50] [Server thread/WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:722)
[19:10:50] [Server thread/WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[19:10:50] [Server thread/WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653)
[19:10:50] [Server thread/WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556)
[19:10:50] [Server thread/WARN]:        at java.lang.Thread.run(Unknown Source)
[19:10:50] [Server thread/WARN]: java.lang.NoSuchFieldException: isStatic
[19:10:50] [Server thread/WARN]:        at java.lang.Class.getField(Unknown Source)
[19:10:50] [Server thread/WARN]:        at codes.rusty.nightlamp.util.WorldUtil.setStatic(WorldUtil.java:112)
[19:10:50] [Server thread/WARN]:        at codes.rusty.nightlamp.util.WorldUtil.setLampState(WorldUtil.java:29)
[19:10:50] [Server thread/WARN]:        at codes.rusty.nightlamp.tasks.LampSetStateTask.run(LampSetStateTask.java:18)
[19:10:50] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[19:10:50] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[19:10:50] [Server thread/WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:722)
[19:10:50] [Server thread/WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[19:10:50] [Server thread/WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653)
[19:10:50] [Server thread/WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556)
[19:10:50] [Server thread/WARN]:        at java.lang.Thread.run(Unknown Source)
[19:10:54] [Server thread/INFO]: fehlfarben issued server command: /savelamps
[19:10:54] [Server thread/INFO]: [NightLamp] The block database has been saved succesfully.

**Comment by ChrissW-R1** [comment]
Solved with pull request #3
